---
variables:
  PYTHON_VERSION: "${PYTHON_VERSION:-3-slim}"

deploy-image:
  stage: deploy
  tags:
    - cloud
  image: docker:stable
  services:
    - docker:dind
  variables:
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: ""
    IMAGE_VERSION: $CI_REGISTRY_IMAGE:latest
  before_script:
    - "docker info"
    - 'docker login -u gitlab-ci-token -p "$CI_JOB_TOKEN" "$CI_REGISTRY"'
  script:
    - 'echo "PYTHON .: $PYTHON_VERSION"'
    - 'echo "IMAGE ..: $IMAGE_VERSION"'
    - 'docker build --tag "$IMAGE_VERSION" --build-arg PYTHON_VERSION="$PYTHON_VERSION" .'
    - 'docker push "$IMAGE_VERSION"'
