---
variables:
  PYTHON_VERSION: "${PYTHON_VERSION:-3}"

deploy-image:
  stage: deploy
  tags:
    - cloud
  image: docker:stable
  services:
    - docker:dind
  variables:
    DOCKER_HOST: tcp://docker:2375/
    DOCKER_DRIVER: overlay2
    IMAGE_VERSION: $CI_REGISTRY_IMAGE:latest
  before_script:
    - docker info
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
  script:
    - echo "$IMAGE_VERSION"
    - docker build --tag "$IMAGE_VERSION" .
    - docker push "$IMAGE_VERSION"
